# in this file i finde the best solotiion to my model.

## import lib need

In [1]:
import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

## how make df

In [7]:
# current_dir = os.path.dirname(os.path.abspath(__file__))
# data_path = os.path.join(current_dir, "data_set_snake_game.csv")
df = pd.read_csv("data_set_snake_game.csv")
df = pd.get_dummies(df, columns=['direction'])

distans = []
current_distance = 1e+4
for i in range(1,len(df)):
    
    next_distance = int(np.sqrt(np.pow(df.loc[i]['head_x'] - df.loc[i]['food_x'],2) + np.pow(df.loc[i]['head_y'] - df.loc[i]['food_y'],2)))
    if current_distance < next_distance:
        # print("current_distance: %s, next_distance: %s" %(current_distance, next_distance))
        df = df.drop(index=i-1)
    current_distance = next_distance
df.reset_index()
df.head(10)

head_x  head_y  food_x  food_y  direction_Down  direction_Left  \
0      25      50     125     250            True           False   
1      25      75     125     250            True           False   
2      25     100     125     250            True           False   
3      25     125     125     250            True           False   
4      25     150     125     250            True           False   
5      25     175     125     250            True           False   
6      25     200     125     250            True           False   
7      25     225     125     250            True           False   
8      25     250     125     250            True           False   
9      50     250     125     250           False           False   

   direction_Right  direction_Up  
0            False         False  
1            False         False  
2            False         False  
3            False         False  
4            False         False  
5            False         False  
6            False         False  
7            False         False  
8            False         False  
9             True         False

## send data to torch

In [6]:
x = df[['head_x' ,'head_y', 'food_x', 'food_y']].values.astype('float32')
y = df[['direction_Down',	'direction_Left','direction_Right',	'direction_Up']].values
y_labels = y.argmax(axis=1).astype('int64')
print(x)

[[ 25.  50. 125. 250.]
 [ 25.  75. 125. 250.]
 [ 25. 100. 125. 250.]
 [ 25. 125. 125. 250.]
 [ 25. 150. 125. 250.]
 [ 25. 175. 125. 250.]
 [ 25. 200. 125. 250.]
 [ 25. 225. 125. 250.]
 [ 25. 250. 125. 250.]
 [ 50. 250. 125. 250.]
 [ 75. 250. 125. 250.]
 [125. 250. 750. 100.]
 [150. 250. 750. 100.]
 [175. 250. 750. 100.]
 [200. 250. 750. 100.]
 [225. 250. 750. 100.]
 [250. 250. 750. 100.]
 [275. 250. 750. 100.]
 [300. 250. 750. 100.]
 [325. 250. 750. 100.]
 [350. 250. 750. 100.]
 [375. 250. 750. 100.]
 [400. 250. 750. 100.]
 [425. 250. 750. 100.]
 [450. 250. 750. 100.]
 [475. 250. 750. 100.]
 [500. 250. 750. 100.]
 [525. 250. 750. 100.]
 [550. 250. 750. 100.]
 [575. 250. 750. 100.]
 [600. 250. 750. 100.]
 [625. 250. 750. 100.]
 [650. 250. 750. 100.]
 [675. 250. 750. 100.]
 [700. 250. 750. 100.]
 [725. 250. 750. 100.]
 [725. 225. 750. 100.]
 [725. 200. 750. 100.]
 [725. 175. 750. 100.]
 [725. 150. 750. 100.]
 [725. 125. 750. 100.]
 [650.  75. 750. 100.]
 [675.  75. 750. 100.]
 [700.  75.